package-lock.json
package.json
src/fixtures.js
src/keys.js
src/keys.test.js
src/paths.js
src/paths.test.js
src/utils.js
src/utils.test.js

These are generalized utilities that have been refactored out of the ledger wallet update https://github.com/unchained-capital/unchained-wallets/pull/17
New utilities:
- `isKeyCompressed`
- `getFingerprintFromPublicKey`
- `deriveExtendedPublicKey`
- `getParentPath`
- `hash160`
these are all used for exporting xpubs from a ledger which does not give a straightforward way of retrieving xpubs out of the box and so require some data manipulation and two rounds of requests from the device (need to get the pubkey from parent node in addition to request at derivation path). These updates handle all data manipulation while ledger device interactions are done in `unchained-wallets` PR 17

xpub utils

---

package-lock.json
src/fees.test.js
src/fixtures.js
src/keys.test.js
src/p2wsh.js
src/p2wsh.test.js

This gets to the correct calculation for a 2-of-3 multisig with 2 inputs and 2 outputs as calculated by the bitcoind rpc and estimated at blockstream.info. The new test I added was failing before this change. 
I wasn't too sure how the `overhead` value is derived, but it did look like based on the bitcoin core docs [here](https://bitcoincore.org/en/segwit_wallet_dev#transaction-fee-estimation) that new segwit fields for marker and flag needed to be included in the witness part of the calculation (i.e. in the discount). Adding that seemed to fix the calcluation.

include marker and version bytes in fee estimation for P2WSH

---

src/keys.js
src/keys.test.js

Given the existing fingerprint functionality, here we add a function to output a fixed-length, zero-padded, hex string that is exactly eight characters in length.
Unit tests included. Updated some of the jsdocs as well.

Adds `fingerprintToFixedLengthHex` function and tests

---

src/keys.js

Missing base58String when generate ExtendedPublicKey from base58 which will cause exception when generating Braid for multisig usage

Cobo Vault integration

---

src/fixtures.js
src/signatures.js

An `S` value can be fewer than 32 bytes in length, in which case it needs to be zero padded when added to signature buffer to allow for proper validation. This is a relatively rare case, but we ran into it when testing.

Fixes a validation issue when creating the Signature Buffer

---

src/keys.js
src/keys.test.js

In this small PR, we extend the functionality of the validatePublicKey function, by allowing it to accept an addressType parameter.
As we know, uncompressed public keys in general are valid public keys...
However uncompressed public keys are not valid for P2WSH and P2SH-P2WSH! 
This extension of the validatePublicKey function will be used in [THIS PR](https://github.com/unchained-capital/caravan/pull/205) to fix [THIS ISSUE](https://github.com/unchained-capital/caravan/issues/164)
NOTE: validatePublicKey will of course be backwards compatible. ie if no addressType is supplied, validatePublicKey will function as previously! The test cases confirm this.

extend validatePublicKey to accept addressType parameter

---

src/psbt.js

Since we're needing this data in other places, it seemed useful to export as a constant. It also helps to self-document when it's being used rather than just look like a random hex string.

export psbt magic

---

src/fixtures.js
src/inputs.js
src/multisig.js
src/psbt.js

I found that this project was having trouble getting built in typescript files (namely unchained-wallets in this case) because it would run into some namespace issues with declaration files that were generated from the jsdoc documentation. In particular it didn't like the `typedef module:...` because it would create a type of `module` that it would export from the module. 
I have to test still if this actually breaks some of the documentation generation (at worst it's probably just the linking). But I've confirmed it does allow it to get built in unchained-wallets when converting that library to typescript

fix: remove module from typedef interfering with d.ts exports

---

.gitignore
src/fixtures.js
src/keys.test.js
src/keys.ts

It's kind of concerning that the type conflict was able to sneak through and didn't seem to be causing many problems anywhere else. I caught it in going through the test suite where the assertion in the ExtendedPublicKey class instantiation was throwing on trying to decode the xpub. 
We also had mismatches in our test suites between paths that were being used for testnet tests using coin types that were mainnet (`0`) instead of testnet (`1`). Ledger is opinionated about that now and so was failing. I updated the caravan test suite to use the right paths [here](https://github.com/unchained-capital/caravan/commit/8ec00d9b60995f3dfb6b249ae41b550218d76aa1) but the fixtures were missing the xpubs to compare against so I added them [here](https://github.com/unchained-capital/unchained-bitcoin/co …

key and fixture fixes

---

src/braid.js
src/braid.test.js

this is just a small feature update that would've been nice for some of the tooling I built out for wallet registration in https://github.com/unchained-capital/unchained-wallets/pull/89
Most of the changes in this file are from prettier. the `toJSON` and `fromJSON` are the only relevant/functional changes.

feat: adds json util methods to braid

---

src/psbtv2.test.js
src/psbtv2.ts

Somewhat of a prerequisite for an `addSignature` method. Different roles have different permissions. Strictly controlling these will ensure a psbt in a valid state. This change refactors and adds some validation logic for the Creator and Constructor roles.

feat: better PsbtV2 validation to ensure proper PsbtV2s

---

package-lock.json
package.json
src/psbtv2.ts

It should be self explanatory if you look at the diff. witness and redeem scripts were being written as script.

Bug: PsbtV2.addOuput was writing incorrect scripts

---

src/psbtv2.ts

Previously, `PsbtV2.addInput()` was only setting the witness script value from a witnessUtxo to the PSBT_IN_WITNESS_UTXO. This change sets the value to `<64-bit little endian int amount> <compact size uint scriptPubKeylen> <bytes scriptPubKey>` as specified in BIP0174.

PsbtV2.addInput apply proper PSBT_IN_WITNESS_UTXO values

---

src/psbtv2.ts

Some variable names were improper and/or copied from other method definitions. This changes them to be less confusing.

Fix confusing variable names in PsbtV2

---

src/psbtv2.test.js
src/psbtv2.ts

For reasons, a PSBTv2 is invalid if the PSBT_GLOBAL_TX_VERSION is less than 2 (https://github.com/bitcoin/bips/blob/master/bip-0370.mediawiki#cite_note-3). This change enforces such a requirement by throwing if a Creator role (or any other role) attempts to set the value less than 2.
Other implementations may ignore this specification by allowing a PSBTv2 with PSBT_GLOBAL_TX_VERSION set to 1. Compatibility with these implementations may be desired while working with an already created and partially signed psbtV0 on txnv1. To provide this, the static `PsbtV2.FromV0` now takes a bool argument `allowTxnVersion1` which will allow for PSBT_GLOBAL_TX_VERSION to be dangerously set to 1.

PsbtV2.PSBT_GLOBAL_TX_VERSION validation and txnv1 compatibility util

---

package-lock.json
package.json
src/psbtv2.ts

The bufio package supports `BufferReader.readBigI64` since version 1.2.0. This change upgrades the package and fixes the `PsbtV2.PSBT_OUT_AMOUNT` getter so that browsers can use it.

Upgrade bufio to 1.2.0 for browser reads on PsbtV2.PSBT_OUT_AMOUNT

---

src/psbtv2.test.js
src/psbtv2.ts

Sometimes when converting from a psbtV0, valid partialsigs might already be present. This change would add them to the resultant psbtV2.

Set partialSigs from PsbtV2.FromV0

---

src/fixtures.js

Adding this gets uc-bitcoin back in line with Caravan test suite to cover a missing fixture that were causing some tests to fail. 
Caravan will need its dependency bumped. 
This test is currently failing:

fix(fixture): missing fixture for testnet xpub export

---

package.json

adds bip66 to package.json which is referenced in src/signatures.js

fix(package.json): add bip66

---

src/fixtures.js

now that the new ledger app is live we can get mainnet registrations as well. This PR just adds the hmacs for the mainnet quorums, but by doing so it also "turns on" the relevant mainnet tests in the Caravan test suite since those will look for an hmac being present when picking which fixtures to use for the tests. 
Here's a screenshot of the larger number of tests (failures are expected - 1 is for path longer than 6, the other 2 are nested segwit signing which need a fix in ledger to be able to process) 
Here's a view of all the new relevant tests.

feat(fixtures): adds mainnet policy hmacs

---

src/keys.test.js
src/keys.ts

Validation would fail when the network was regtest and the xpub prefix was `tpub`. This adds support for regtest networks and it also cleans up some of the validation code which had some duplication around this.

fix(keys): include regtest for tpub validation

---

package-lock.json
src/outputs.js
src/outputs.test.js

Adjusts `validateOutputAmount` to accept an optional minSats which allows a caller to specify their own dust limit.

Add minSats to the validateOutputAmount function. Fix missing package.

---

package-lock.json
package.json
src/addresses.test.ts
src/addresses.ts

- Update `bitcoin-address-validation` to `2.2.3`
- Adapt to new interace
- Update `addresses.test` to include a taproot example

Update bitcoin-address-validation to v2.x

---

.github/workflows/ci.yml
.github/workflows/release-please.yml

This change adjusts github workflows to match the minimum supported node version. `package.json` indicates that the minimum supported version of node is >= 16, but ci was building for 14 (incompatible) and release-please was building using 18. 
If this change is unacceptable, I would recommend alternatively `package.json` engines entry be updated to >=18 and ci strategy node versions range `['18.x', '20.x']`

Adjust node versions to match minimum supported

---

src/outputs.ts
src/utils.ts

`outputs/validateOutputAmount` is requiring a BigNumber type on its args. This leaks lib dependencies onto the caller. Previously a version of unchained-bitcoin had removed the BigNumber dependency from its API. This function must have been missed.
Unfortunately this change would require a major version increment since an arg type is updating and breaking backward compatibility.

Fix validateOutputAmount API for BigNumber

---

src/fees.test.ts
src/fees.ts
src/types/fees.ts
src/types/index.ts

In order to provide more flexible uses for fee validation, this change introduces fee error types.
Previously, fee validation only returned strings. With validation functions which return an error type, applications using this library will be able to provide their own user feedback based on error type.
The new type `FeeValidationError` is a typescript enum collecting fee validation error categories currently being returned by `validateFee` and `validateFeeRate` functions.
To preserve backward compatibility, `validateFee` and `validateFeeRate` functions are now merely wrappers for more granular functions which return pieces of an error. These new functions are: `checkFeeError`, `checkFeeRateError`, and `getFeeErrorMessage`.
I'm not entirely happy with the naming. I think the ideal names …

Fee error types

---

src/fixtures.ts

Fixtures didn't match wallet configs. Some earlier change must have broken this and the fixtures weren't caught as well. With this change, all relevant tests in the caravan test suite pass (nest segwit signing still doesn't work but that's not related, it was failing w/ a different error previously though)

fix(fixtures): fix hmac fixtures
